name: Generate QR Code

on:
  push:
    paths:
      - GTRALP/GTRALP001.html
      - GTRALP/GTRALP002.html
      - GTRALP/GTRALP003.html
      - GTRALP/GTRALP004.html
      - GTRALP/GTRALP005.html
      - GTRALP/GTRALP006.html
      - GTRALP/GTRALP007.html
      - GTRALP/GTRALP008.html
      - GTRALP/GTRALP009.html
      - GTRALP/GTRALP010.html
      - GTRALP/GTRALP011.html
      - GTRALP/GTRALP012.html
      - GTRALP/GTRALP013.html
      - GTRALP/GTRALP014.html
      - GTRALP/GTRALP015.html
      - generate_qr.py  # Trigger if this script changes (optional)

jobs:
  generate_qr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install qrcode[pil]

      - name: Generate QR Code
        run: python generate_qr.py

      - name: Commit QR Code
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add GTRALP/GTRALP002_qr.png
          git commit -m 'Auto-generate QR code for GTRALP002.html' || echo 'No changes to commit'
          git push
